

service: backend # NOTE: update this with your service name


plugins:
  - serverless-offline
  - serverless-webpack

package:
  individually: true



# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true'

provider:
  name: aws
  runtime: nodejs8.10


functions:
  ecs-list:
    handler: ecs/list.main
    events:
      - http:
          path: ecs/list
          method: get
          cors: true
  ecs-get:
    handler: ecs/get.main
    events:
      - http:
          path: ecs/{arn}
          method: get
          cors: true